**240840116061**

**Practical-3|Apply filtering,sorting,aggregation and GroupBy opertions on real-world dataset**

**step-1:display data set**

In [1]:
# Import Library.
import pandas as pd
# Create Dataset.
df = {
    "EMP_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Neha", "Vivek", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "City": ["Surat", "Navasari", "Surat", "Valsad", "Surat", "Navasari", "Valsad", "Surat"],
    "Salary": [45000, 38000, 52000, 48000, 40000, 51000, 60000, 42000],
    "Experience": [2, 1, 5, 4, 2, 6, 8, 3]
}

df=pd.DataFrame(df)
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

**step-2:filter data**

In [2]:
#2.1Display employees from IT dept.
df[df['Department'] == 'IT']

   EMP_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

In [3]:
# 2.2 Display employees with salary > 50000.
df[df['Salary'] > 50000]

   EMP_ID   Name Department      City  Salary  Experience
2     103   Amit         IT     Surat   52000           5
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8

In [4]:
# 2.3 Display employees from Surat.
df[df['City'] == 'Surat']

   EMP_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

In [5]:
# 2.4 Display employees from IT department having salary > 5000
df[(df['Department'] == 'IT') & (df['Salary'] > 50000)]

   EMP_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**step-3: sort data**

In [6]:
# 3.1: Salary ascending
#sort employees by salary from lowest to highest
df.sort_values('Salary', ascending=True)

   EMP_ID   Name Department      City  Salary  Experience
1     102  Priya         HR  Navasari   38000           1
4     105  Karan         HR     Surat   40000           2
7     108  Pooja         HR     Surat   42000           3
0     101  Rahul         IT     Surat   45000           2
3     104   Riya    Finance    Valsad   48000           4
5     106   Neha    Finance  Navasari   51000           6
2     103   Amit         IT     Surat   52000           5
6     107  Vivek         IT    Valsad   60000           8

In [7]:
# 3.2: Salary descending
#sort employees by salary from highest to lowest
df.sort_values('Salary', ascending=False)

   EMP_ID   Name Department      City  Salary  Experience
6     107  Vivek         IT    Valsad   60000           8
2     103   Amit         IT     Surat   52000           5
5     106   Neha    Finance  Navasari   51000           6
3     104   Riya    Finance    Valsad   48000           4
0     101  Rahul         IT     Surat   45000           2
7     108  Pooja         HR     Surat   42000           3
4     105  Karan         HR     Surat   40000           2
1     102  Priya         HR  Navasari   38000           1

In [8]:
# 3.3: Department-wise and salary descending
#sort employee department wise and within each department sort salary in decending order
df.sort_values(by=['Department', 'Salary'],ascending=[True, False])

   EMP_ID   Name Department      City  Salary  Experience
5     106   Neha    Finance  Navasari   51000           6
3     104   Riya    Finance    Valsad   48000           4
7     108  Pooja         HR     Surat   42000           3
4     105  Karan         HR     Surat   40000           2
1     102  Priya         HR  Navasari   38000           1
6     107  Vivek         IT    Valsad   60000           8
2     103   Amit         IT     Surat   52000           5
0     101  Rahul         IT     Surat   45000           2

**step-4: perform aggrigation**

In [9]:
# 4.1 Calculate the total salary of all employees.
df['Salary'].sum()

np.int64(376000)

In [10]:
#4.2 Calculate thye avg salary of all employees.
df['Salary'].mean()

np.float64(47000.0)

In [11]:
# 4.3 Display max salary.
df['Salary'].max()

60000

In [12]:
# 4.4 Display lowest salary.
df['Salary'].min()

38000

In [13]:
# 4.5 Count the total no of employees.
df['EMP_ID'].count()

np.int64(8)

**step-5: perform GroupBy operation**

In [14]:
# 5.1: Average salary of each department
# grp employees based on department and calculate the avg salary of each department.
df.groupby('Department')['Salary'].mean().reset_index()

  Department        Salary
0    Finance  49500.000000
1         HR  40000.000000
2         IT  52333.333333

In [15]:
# 5.2: Total salary of each department.
# Calculate the total salary paid by each dept.
df.groupby('Department')['Salary'].sum().reset_index()

  Department  Salary
0    Finance   99000
1         HR  120000
2         IT  157000

In [16]:
# 5.3: Highest salary in each department.
# Display the higest salary in each department.
df.groupby('Department')['Salary'].max().reset_index()

  Department  Salary
0    Finance   51000
1         HR   42000
2         IT   60000

In [17]:
# 5.4: Number of employees in each department.
# Count the no of employees in each dept.
df.groupby('Department')['EMP_ID'].count().reset_index()

  Department  EMP_ID
0    Finance       2
1         HR       3
2         IT       3

In [18]:
# 5.5: Average salary in each city.
# Calculate the avg salary of employee in each city.
df.groupby('City')['Salary'].mean().reset_index()

       City   Salary
0  Navasari  44500.0
1     Surat  44750.0
2    Valsad  54000.0

**step-6: multiple aggrigation function**

In [19]:
# 6.1 Apply multiple statistical function to the salary column each dept.
df.groupby('Department')['Salary'].agg(['sum', 'mean', 'max', 'min', 'count']).reset_index()

  Department     sum          mean    max    min  count
0    Finance   99000  49500.000000  51000  48000      2
1         HR  120000  40000.000000  42000  38000      3
2         IT  157000  52333.333333  60000  45000      3

**step-7: save the result in csv file**

In [20]:
# Save CSV
df.to_csv("Employee_Data.csv", index=False)

print("CSV file saved Successfully")

CSV file saved Successfully

**step-8: download the csv file**

In [21]:
# Import the files module from Google Colab
from google.colab import files

#Doenload CSV file
files.download("Employee_Data.csv")