**240840116061**

 **Practical-1 |Study the Data Analytics Lifecycle and perform data acquisition from csv,excel and json files using pandas**

In [1]:
import pandas as pd
#data we create
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "krisha", "Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["Surat", "Navsari", "Vaslad", "Bharuch", "Mumbai", "Banglore", "Pune"],
    "Marks": [84, 78, 97, 69, 78, 80, 90]
}

In [2]:
#convert dictionary into pandas dataframe
df = pd.DataFrame(data)
print(df)

    ID    Name  Age      City  Marks
0  101   Rahul   20     Surat     84
1  102   Priya   21   Navsari     78
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [3]:
#save the dataframe as csv file
df.to_csv("students.csv", index=False)
#display the message
print("csv file is created")

csv file is created

In [4]:
#save the dataframe as excel file
df.to_excel("students.xlsx", index=False)
#display the message
print("excel file is created")

excel file is created

In [5]:
#save the dataframe as json file
df.to_json("students.json", index=False)
#display the message
print("json file is created")

json file is created

In [6]:
#display csv file
df_csv = pd.read_csv("students.csv")
print(df_csv)

    ID    Name  Age      City  Marks
0  101   Rahul   20     Surat     84
1  102   Priya   21   Navsari     78
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [7]:
#display excel file
df_excel = pd.read_excel("students.xlsx")
print(df_excel)

    ID    Name  Age      City  Marks
0  101   Rahul   20     Surat     84
1  102   Priya   21   Navsari     78
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [8]:
#display json file
df_json = pd.read_json("students.json")
print(df_json)

    ID    Name  Age      City  Marks
0  101   Rahul   20     Surat     84
1  102   Priya   21   Navsari     78
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [9]:
#to show file 5 recoreds
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     84
1  102  Priya   21  Navsari     78
2  103   Amit   19   Vaslad     97
3  104   Riya   20  Bharuch     69
4  105  Karan   22   Mumbai     78

In [10]:
#To show file last 5 recored
df_csv.tail()

    ID    Name  Age      City  Marks
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [11]:
#to show file first 5 recoreds
df_excel.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     84
1  102  Priya   21  Navsari     78
2  103   Amit   19   Vaslad     97
3  104   Riya   20  Bharuch     69
4  105  Karan   22   Mumbai     78

In [12]:
#to show file last 5 recoreds
df_excel.tail()

    ID    Name  Age      City  Marks
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [13]:
#to show file first 5 recoreds
df_json.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     84
1  102  Priya   21  Navsari     78
2  103   Amit   19   Vaslad     97
3  104   Riya   20  Bharuch     69
4  105  Karan   22   Mumbai     78

In [14]:
#to show file last 5 recoreds
df_json.tail()

    ID    Name  Age      City  Marks
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [15]:
#for displaying file info
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

In [16]:
# for displaying file statistical data
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  82.285714
std      2.160247   3.109126   9.105205
min    101.000000  19.000000  69.000000
25%    102.500000  20.000000  78.000000
50%    104.000000  21.000000  80.000000
75%    105.500000  23.000000  87.000000
max    107.000000  28.000000  97.000000

In [17]:
#display database shape in tuple
df_csv.shape

(7, 5)

In [18]:
#display columns name
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [19]:
# display data type
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

In [20]:
#count the missing values
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

In [26]:
#display only the particular column.
df_csv[["Age", "Name"]]

   Age    Name
0   20   Rahul
1   21   Priya
2   19    Amit
3   20    Riya
4   22   Karan
5   24  krisha
6   28   Harry

In [22]:
#Display the name of student age greater than 21.
df_csv[df_csv["Age"] > 21]

    ID    Name  Age      City  Marks
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90

In [23]:
#calculate the avg of student age
df_csv["Age"].mean()

np.float64(22.0)

In [24]:
#sort the dataset marks in decending
df_csv.sort_values(by="Marks",ascending=False)

    ID    Name  Age      City  Marks
2  103    Amit   19    Vaslad     97
6  107   Harry   28      Pune     90
0  101   Rahul   20     Surat     84
5  106  krisha   24  Banglore     80
1  102   Priya   21   Navsari     78
4  105   Karan   22    Mumbai     78
3  104    Riya   20   Bharuch     69

In [25]:
#display csv file
print(df_csv)

    ID    Name  Age      City  Marks
0  101   Rahul   20     Surat     84
1  102   Priya   21   Navsari     78
2  103    Amit   19    Vaslad     97
3  104    Riya   20   Bharuch     69
4  105   Karan   22    Mumbai     78
5  106  krisha   24  Banglore     80
6  107   Harry   28      Pune     90