**240840116061**

**practical-2| perform data inspection, cleaning,handling missing values, remove
duplicate values and data transformation using pandas**

In [2]:
#importing pandas library
import pandas as pd

data = {
    "ID" : [ 101, 102, 103, 104, 104, 105, 106, 107],
    "Name" : ["Rahul", "Priya", "Amit", None, "Riya", "Ajay", "Naresh", "Jenil"],
    "Age" : [20, 21, None, 20, 20, 22, 23, 28],
    "City" : ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks" : [85, None, 78, 88, 88, 81, 90, 93]
}
df = pd.DataFrame(data)
print(df)

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

In [3]:
#display the first 5 records of dataset
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [4]:
#display the last 5 records of dataset
df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

In [5]:
#display the detail infromation of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [6]:
#display the stastistical of dataset
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [7]:
#display the dimension of dataset
df.shape

(8, 5)

In [8]:
#display the datatype of each column
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [9]:
#display all the column of dataset
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [10]:
#check missing values
df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [11]:
#check missing values with number
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [12]:
#print the total no. of null
df.isnull().sum().sum()

np.int64(3)

In [13]:
#fill the missing values in marks column
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [14]:
#replace the missing value in age column
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [15]:
#replace the null values in name column
df["Name"] = df["Name"].fillna("Manan")
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104   Manan  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [16]:
#detect duplicate
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [17]:
#count the no. of duplicated rows
df.duplicated().sum()

np.int64(0)

In [18]:
#remove the duplicated records
df.drop_duplicates()

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104   Manan  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [19]:
#rename the column "Marks" to "score".
df.rename(columns={"Marks":"Score"}, inplace=True)
df

    ID    Name   Age       City      Score
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104   Manan  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [20]:
#convert the age column from float to integer
df["Age"] = df["Age"].astype(int)
display(df)

    ID    Name  Age       City      Score
0  101   Rahul   20      Surat  85.000000
1  102   Priya   21    Navsari  86.142857
2  103    Amit   22      Surat  78.000000
3  104   Manan   20    Bharuch  88.000000
4  104    Riya   20    Bharuch  88.000000
5  105    Ajay   22    Navsari  81.000000
6  106  Naresh   23      Surat  90.000000
7  107   Jenil   28  Ahmedabad  93.000000

In [21]:
#create a new column named Final score
df["Final_Score"] = df["Score"] + 5
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   Rahul   20      Surat  85.000000    90.000000
1  102   Priya   21    Navsari  86.142857    91.142857
2  103    Amit   22      Surat  78.000000    83.000000
3  104   Manan   20    Bharuch  88.000000    93.000000
4  104    Riya   20    Bharuch  88.000000    93.000000
5  105    Ajay   22    Navsari  81.000000    86.000000
6  106  Naresh   23      Surat  90.000000    95.000000
7  107   Jenil   28  Ahmedabad  93.000000    98.000000

In [22]:
#convert all student names into uppercase
df["Name"] = df["Name"].str.upper()
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      Surat  85.000000    90.000000
1  102   PRIYA   21    Navsari  86.142857    91.142857
2  103    AMIT   22      Surat  78.000000    83.000000
3  104   MANAN   20    Bharuch  88.000000    93.000000
4  104    RIYA   20    Bharuch  88.000000    93.000000
5  105    AJAY   22    Navsari  81.000000    86.000000
6  106  NARESH   23      Surat  90.000000    95.000000
7  107   JENIL   28  Ahmedabad  93.000000    98.000000

In [23]:
#convert all city names into lowercase
df["City"] = df["City"].str.lower()
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   22      surat  78.000000    83.000000
3  104   MANAN   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahmedabad  93.000000    98.000000

In [24]:
#remove extra space from city column
df["City"] = df["City"].str.strip()
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   22      surat  78.000000    83.000000
3  104   MANAN   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahmedabad  93.000000    98.000000

In [27]:
#remove extra space from name column from right
df["Name"] = df["Name"].str.rstrip()
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   22      surat  78.000000    83.000000
3  104   MANAN   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahmedabad  93.000000    98.000000

In [28]:
#remove extra space from name column from left
df["Name"] = df["Name"].str.lstrip()
display(df)

    ID    Name  Age       City      Score  Final_Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   22      surat  78.000000    83.000000
3  104   MANAN   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
5  105    AJAY   22    navsari  81.000000    86.000000
6  106  NARESH   23      surat  90.000000    95.000000
7  107   JENIL   28  ahmedabad  93.000000    98.000000

In [25]:
#sort the dataset based on final_score
df.sort_values(by="Final_Score", ascending=False)

    ID    Name  Age       City      Score  Final_Score
7  107   JENIL   28  ahmedabad  93.000000    98.000000
6  106  NARESH   23      surat  90.000000    95.000000
3  104   MANAN   20    bharuch  88.000000    93.000000
4  104    RIYA   20    bharuch  88.000000    93.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
0  101   RAHUL   20      surat  85.000000    90.000000
5  105    AJAY   22    navsari  81.000000    86.000000
2  103    AMIT   22      surat  78.000000    83.000000

In [26]:
#save the cleaned dataset in csv
df.to_csv("cleaned_data.csv", index=False)
print("Data saved successfully")

Data saved successfully